In [10]:
%pip install torch


  Using cached setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
    --------------------------------------- 1.8/124.1 MB 8.4 MB/s eta 0:00:15
   - -------------------------------------- 3.4/124.1 MB 8.0 MB/s eta 0:00:16
   - -------------------------------------- 3.7/124.1 MB 8.1 MB/s eta 0:00:15
   - -------------------------------------- 3.7/124.1 MB 8.1 MB/s eta 0:00:15
   - -------------------------------------- 4.2/124.1 MB 4.0 MB/s eta 0:00:31
   - -------------------------------------- 4.5/124.1 MB 3.7 MB/s eta 0:00:33
   - -------------------------------------- 4.7/124.1 MB 3.5 MB/s eta 0:00:35
   - -------------------------------------- 5.2/124.1 MB 3.2 MB/s eta 0:00:38
   - ------------------------------------

In [3]:
#1--------------------------------------------------------
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [19]:
# Création à partir d'un tableau NumPy
array_np = np.array([[1, 2], [3, 4]])
tensor_tf_np = tf.constant(array_np)
print("TensorFlow (NumPy):", tensor_tf_np)

TensorFlow (NumPy): tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


In [20]:
# Initialisation avec des valeurs spécifiques
zeros_tf = tf.zeros((2, 3))
ones_tf = tf.ones((3, 2))
random_tf = tf.random.normal((2, 2))

In [23]:
print("TensorFlow (Zeros):", zeros_tf)
print("TensorFlow (Ones):", ones_tf)
print("TensorFlow (Random Normal):" ,random_tf)

TensorFlow (Zeros): tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
TensorFlow (Ones): tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
TensorFlow (Random Normal): tf.Tensor(
[[-0.44939855 -0.20892797]
 [-0.13011982  1.2163477 ]], shape=(2, 2), dtype=float32)


In [ ]:
#2-------------------------------------------------------------
#keras utilise les tensor Tensorflow sous les capot
tensor_keras = tf.constant([6,4,6,8,3,2,1])
print('keras (tensorflow tensor):',tensor_keras)

In [8]:
#vavaible keras (uitil pour les parametre entrenable)
variable_keras = tf.Variable(tf.random.normal((2,2)))
print('keras varaible:',variable_keras)

keras varaible: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.77440816,  1.1326069 ],
       [-0.15323679, -0.5130444 ]], dtype=float32)>


In [11]:
#2-----------------------------------------------
import numpy as np 
import torch as tc

In [13]:
# creesion a partir d'une liste python 
tesor_torch_liste = tc.tensor([1,2,3,4,5,6])
print('pytorch (liste):', tesor_torch_liste)

pytorch (liste): tensor([1, 2, 3, 4, 5, 6])


In [15]:
#creetion a partir d'une tableu numpy
array_np = np.array([[1,2],[3,4]])
tensor_torch_np = tc.tensor(array_np)
print('pytorch_numpy',tensor_torch_np)

pytorch_numpy tensor([[1, 2],
        [3, 4]])


In [27]:
# Initialisation avec des valeurs spécifiques
zeros_torch = tc.zeros((2, 3))
ones_torch = tc.ones((3, 2))
random_torch = tc.randn((2, 2))

print("PyTorch (Zeros):", zeros_torch)
print("PyTorch (Ones):", ones_torch)
print("PyTorch (Random Normal):", random_torch)

PyTorch (Zeros): tensor([[0., 0., 0.],
        [0., 0., 0.]])
PyTorch (Ones): tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
PyTorch (Random Normal): tensor([[-0.6973,  0.0643],
        [ 1.7389, -0.6891]])


In [29]:
#3--------------------------------------------------
import tensorflow as tf

tensor_a_tf = tf.constant([[1, 2], [3, 4]])
tensor_b_tf = tf.constant([[5, 6], [7, 8]])

In [36]:
# Addition et Multiplication
add_tf = tf.add(tensor_a_tf, tensor_b_tf)
multiply_tf = tf.multiply(tensor_a_tf, tensor_b_tf) #Element-wise multiplication
print("TensorFlow (Addition):", add_tf)
print("TensorFlow (Element-wise Multiplication):", multiply_tf)

TensorFlow (Addition): tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
TensorFlow (Element-wise Multiplication): tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [37]:
# Produit matriciel (ligne x colum)
matmul_tf = tf.matmul(tensor_a_tf, tensor_b_tf)
print("TensorFlow (Matmul):",matmul_tf)

TensorFlow (Matmul): tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [38]:
# Redimensionnement
reshape_tf = tf.reshape(tensor_a_tf, (4, 1))
print("TensorFlow (Reshape):", reshape_tf)

TensorFlow (Reshape): tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)


In [41]:
# Concaténation
concat_tf = tf.concat([tensor_a_tf, tensor_b_tf], axis=0) # Concaténation sur les lignes
print("TensorFlow (Concatenation):",concat_tf)

TensorFlow (Concatenation): tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


In [42]:
#4-------------------------------------
import tensorflow as tf
from tensorflow import keras

# Keras utilise les fonctions TensorFlow
tensor_a_keras = tf.constant([[1, 2], [3, 4]])
tensor_b_keras = tf.constant([[5, 6], [7, 8]])

In [43]:
add_keras = tf.add(tensor_a_keras, tensor_b_keras)
multiply_keras = tf.multiply(tensor_a_keras, tensor_b_keras) #Element-wise multiplication
matmul_keras = tf.matmul(tensor_a_keras, tensor_b_keras)
reshape_keras = tf.reshape(tensor_a_keras, (4, 1))
concat_keras = tf.concat([tensor_a_keras, tensor_b_keras], axis=0)

In [44]:
print(f"Keras (Addition): {add_keras}")
print(f"Keras (Element-wise Multiplication): {multiply_keras}")
print(f"Keras (Matmul): {matmul_keras}")
print(f"Keras (Reshape): {reshape_keras}")
print(f"Keras (Concatenation): {concat_keras}")

Keras (Addition): [[ 6  8]
 [10 12]]
Keras (Element-wise Multiplication): [[ 5 12]
 [21 32]]
Keras (Matmul): [[19 22]
 [43 50]]
Keras (Reshape): [[1]
 [2]
 [3]
 [4]]
Keras (Concatenation): [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
#5-------------------------------------
import tensorflow as tf

tensor_a_tf = tf.constant([[1, 2], [3, 4]])
tensor_b_tf = tf.constant([[5, 6], [7, 8]])

In [46]:
# Addition et Multiplication
add_tf = tf.add(tensor_a_tf, tensor_b_tf)
multiply_tf = tf.multiply(tensor_a_tf, tensor_b_tf) #Element-wise multiplication

# Produit matriciel
matmul_tf = tf.matmul(tensor_a_tf, tensor_b_tf)

# Redimensionnement
reshape_tf = tf.reshape(tensor_a_tf, (4, 1))

# Concaténation
concat_tf = tf.concat([tensor_a_tf, tensor_b_tf], axis=0) # Concaténation sur les lignes

In [47]:
print(f"TensorFlow (Addition): {add_tf}")
print(f"TensorFlow (Element-wise Multiplication): {multiply_tf}")
print(f"TensorFlow (Matmul): {matmul_tf}")
print(f"TensorFlow (Reshape): {reshape_tf}")
print(f"TensorFlow (Concatenation): {concat_tf}")

TensorFlow (Addition): [[ 6  8]
 [10 12]]
TensorFlow (Element-wise Multiplication): [[ 5 12]
 [21 32]]
TensorFlow (Matmul): [[19 22]
 [43 50]]
TensorFlow (Reshape): [[1]
 [2]
 [3]
 [4]]
TensorFlow (Concatenation): [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
#6---------------------------------------------
tensor_a_torch = tc.tensor([[1, 2], [3, 4]])
tensor_b_torch = tc.tensor([[5, 6], [7, 8]])

In [52]:
# Addition et Multiplication
add_torch = tc.add(tensor_a_torch, tensor_b_torch)
multiply_torch = tc.mul(tensor_a_torch, tensor_b_torch) #Element-wise multiplication

# Produit matriciel
matmul_torch = tc.matmul(tensor_a_torch, tensor_b_torch)

# Redimensionnement
reshape_torch = tensor_a_torch.reshape((4, 1))

# Concaténation
concat_torch = tc.cat([tensor_a_torch, tensor_b_torch], dim=0) # Concaténation sur les lignes

In [53]:
print(f"PyTorch (Addition): {add_torch}")
print(f"PyTorch (Element-wise Multiplication): {multiply_torch}")
print(f"PyTorch (Matmul): {matmul_torch}")
print(f"PyTorch (Reshape): {reshape_torch}")
print(f"PyTorch (Concatenation): {concat_torch}")

PyTorch (Addition): tensor([[ 6,  8],
        [10, 12]])
PyTorch (Element-wise Multiplication): tensor([[ 5, 12],
        [21, 32]])
PyTorch (Matmul): tensor([[19, 22],
        [43, 50]])
PyTorch (Reshape): tensor([[1],
        [2],
        [3],
        [4]])
PyTorch (Concatenation): tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [54]:
#etape 3
#1 tensorflow
import tensorflow as tf
tensor_tf = tf.constant([[1, 2, 3], [4, 5, 6]])

# Obtenir le shape
shape_tf = tf.shape(tensor_tf)
print(f"TensorFlow (Shape): {shape_tf}")

TensorFlow (Shape): [2 3]


In [55]:
# Redimensionner
reshaped_tf = tf.reshape(tensor_tf, (3, 2))
print(f"TensorFlow (Reshaped): {reshaped_tf}")

TensorFlow (Reshaped): [[1 2]
 [3 4]
 [5 6]]


In [57]:
#2 keras
tensor_keras = tf.constant([[1, 2, 3], [4, 5, 6]])
shape_keras = tf.shape(tensor_keras)
print(f"Keras (Shape): {shape_keras}")

Keras (Shape): [2 3]


In [58]:
reshaped_keras = tf.reshape(tensor_keras, (3, 2))
print(f"Keras (Reshaped): {reshaped_keras}")

Keras (Reshaped): [[1 2]
 [3 4]
 [5 6]]


In [59]:
# 3 torch
import torch

tensor_torch = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [60]:
# Obtenir le shape
shape_torch = tensor_torch.shape
print(f"PyTorch (Shape): {shape_torch}")

PyTorch (Shape): torch.Size([2, 3])


In [61]:
# Redimensionner
reshaped_torch = tensor_torch.reshape((3, 2))
print(f"PyTorch (Reshaped): {reshaped_torch}")

PyTorch (Reshaped): tensor([[1, 2],
        [3, 4],
        [5, 6]])
